<?php

$usersData = [
    [
        'restaurant_name' => 'Ristorante del Parco',
        'email' => 'info@ristorantedelparco.com',
        'address' => 'Via Roma, 123',
        'vat_number' => 'IT12345678901',
        'phone_number' => '123-456-7890',
        'img' => 'uploads/ristorante_del_parco.jpg',
        'password' => bcrypt('password1'),
    ],
    [
        'restaurant_name' => 'La Trattoria Italiana',
        'email' => 'info@latrattoriaitaliana.com',
        'address' => 'Piazza Garibaldi, 45',
        'vat_number' => 'IT98765432109',
        'phone_number' => '987-654-3210',
        'img' => 'uploads/la_trattoria_italiana.jpg',
        'password' => bcrypt('password2'),
    ],
    [
        'restaurant_name' => 'Ristorante Buona Tavola',
        'email' => 'info@buonatavola.com',
        'address' => 'Via Milano, 78',
        'vat_number' => 'IT45678901234',
        'phone_number' => '456-789-0123',
        'img' => 'uploads/ristorante_buona_tavola.jpg',
        'password' => bcrypt('password3'),
    ],
    [
        'restaurant_name' => 'Pizzeria Napoli',
        'email' => 'info@pizzerianapoli.com',
        'address' => 'Corso Vittorio Emanuele, 56',
        'vat_number' => 'IT78901234567',
        'phone_number' => '789-012-3456',
        'img' => 'uploads/pizzeria_napoli.jpg',
        'password' => bcrypt('password4'),
    ],
    [
        'restaurant_name' => 'Sapore di Mare',
        'email' => 'info@saporedimare.com',
        'address' => 'Lungomare Kennedy, 12',
        'vat_number' => 'IT23456789012',
        'phone_number' => '234-567-8901',
        'img' => 'uploads/sapore_di_mare.jpg',
        'password' => bcrypt('password5'),
    ],
    [
        'restaurant_name' => 'Osteria delle Colline',
        'email' => 'info@osteriadellecolline.com',
        'address' => 'Via Montepulciano, 34',
        'vat_number' => 'IT56789012345',
        'phone_number' => '567-890-1234',
        'img' => 'uploads/osteria_delle_colline.jpg',
        'password' => bcrypt('password6'),
    ],
    [
        'restaurant_name' => 'Ristorante Gusto Toscano',
        'email' => 'info@gustotoscano.com',
        'address' => 'Piazza Dante, 21',
        'vat_number' => 'IT89012345678',
        'phone_number' => '890-123-4567',
        'img' => 'uploads/ristorante_gusto_toscano.jpg',
        'password' => bcrypt('password7'),
    ],
    [
        'restaurant_name' => 'Trattoria della Nonna',
        'email' => 'info@trattoriadellanonna.com',
        'address' => 'Via della Repubblica, 7',
        'vat_number' => 'IT34567890123',
        'phone_number' => '345-678-9012',
        'img' => 'uploads/trattoria_della_nonna.jpg',
        'password' => bcrypt('password8'),
    ],
    [
        'restaurant_name' => 'Ristorante La Perla',
        'email' => 'info@ristorantelaperla.com',
        'address' => 'Corso Cavour, 88',
        'vat_number' => 'IT67890123456',
        'phone_number' => '678-901-2345',
        'img' => 'uploads/ristorante_la_perla.jpg',
        'password' => bcrypt('password9'),
    ],
    [
        'restaurant_name' => 'Pizzeria Bella Napoli',
        'email' => 'info@bellanapoli.com',
        'address' => 'Via Vesuvio, 123',
        'vat_number' => 'IT90123456789',
        'phone_number' => '901-234-5678',
        'img' => 'uploads/pizzeria_bella_napoli.jpg',
        'password' => bcrypt('password10'),
    ],
    [
        'restaurant_name' => 'Pizza da Michele',
        'email' => 'info@pizzadamichele.com',
        'address' => 'Via Margherita, 50',
        'vat_number' => 'IT10234567890',
        'phone_number' => '102-345-6789',
        'img' => 'uploads/pizza_da_michele.jpg',
        'password' => bcrypt('password11'),
    ],
    [
        'restaurant_name' => 'Primi Piatti Paradiso',
        'email' => 'info@primipiattparadiso.com',
        'address' => 'Via Risotto, 92',
        'vat_number' => 'IT11234567890',
        'phone_number' => '112-345-6789',
        'img' => 'uploads/primi_piatti_paradiso.jpg',
        'password' => bcrypt('password12'),
    ],
    [
        'restaurant_name' => 'Pasta e Pesto',
        'email' => 'info@pasta-e-pesto.com',
        'address' => 'Piazza Linguine, 16',
        'vat_number' => 'IT12234567890',
        'phone_number' => '122-345-6789',
        'img' => 'uploads/pasta_e_pesto.jpg',
        'password' => bcrypt('password13'),
    ],
    [
        'restaurant_name' => 'Piadina Ciliegia',
        'email' => 'info@piadinaciliegia.com',
        'address' => 'Via del Ciliegio, 44',
        'vat_number' => 'IT13234567890',
        'phone_number' => '132-345-6789',
        'img' => 'uploads/piadina_romagnola.jpg',
        'password' => bcrypt('password14'),
    ],
    [
        'restaurant_name' => 'Carne & Grill',
        'email' => 'info@carneegrill.com',
        'address' => 'Corso Bistecca, 22',
        'vat_number' => 'IT14234567890',
        'phone_number' => '142-345-6789',
        'img' => 'uploads/carne_e_grill.jpg',
        'password' => bcrypt('password15'),
    ],
    [
        'restaurant_name' => 'Pesce Fresco Marina',
        'email' => 'info@pescefresco.com',
        'address' => 'Lungomare Sirena, 3',
        'vat_number' => 'IT15234567890',
        'phone_number' => '152-345-6789',
        'img' => 'uploads/pesce_fresco_marina.jpg',
        'password' => bcrypt('password16'),
    ],
    [
        'restaurant_name' => 'Green & Veggie',
        'email' => 'info@greenveggie.com',
        'address' => 'Piazza Verdura, 18',
        'vat_number' => 'IT16234567890',
        'phone_number' => '162-345-6789',
        'img' => 'uploads/green_veggie.jpg',
        'password' => bcrypt('password17'),
    ],
    [
        'restaurant_name' => 'Vegan Vibes',
        'email' => 'info@veganvibes.com',
        'address' => 'Via Tofu, 29',
        'vat_number' => 'IT17234567890',
        'phone_number' => '172-345-6789',
        'img' => 'uploads/vegan_vibes.jpg',
        'password' => bcrypt('password18'),
    ],
    [
        'restaurant_name' => 'Senza Glutine Delizia',
        'email' => 'info@senzaglutinedelizia.com',
        'address' => 'Corso Intoleranze, 65',
        'vat_number' => 'IT18234567890',
        'phone_number' => '182-345-6789',
        'img' => 'uploads/senza_glutine_delizia.jpg',
        'password' => bcrypt('password19'),
    ],
    [
        'restaurant_name' => 'Vegano e Gluten-Free Bistro',
        'email' => 'info@veganoglutenfree.com',
        'address' => 'Via Salute, 77',
        'vat_number' => 'IT19234567890',
        'phone_number' => '192-345-6789',
        'img' => 'uploads/veganoglutenfree_bistro.jpg',
        'password' => bcrypt('password20'),
    ],
    [
        'restaurant_name' => 'Pizzeria Vesuvio',
        'email' => 'info@pizzeriavesuvio.com',
        'address' => 'Via Chiaia, 23',
        'vat_number' => 'IT20234567890',
        'phone_number' => '202-345-6789',
        'img' => 'uploads/pizzeria_vesuvio.jpg',
        'password' => bcrypt('password21'),
    ],
    [
        'restaurant_name' => 'Roma Pasta Boutique',
        'email' => 'info@romapastaboutique.com',
        'address' => 'Via del Corso, 89',
        'vat_number' => 'IT21234567890',
        'phone_number' => '212-345-6789',
        'img' => 'uploads/roma_pasta_boutique.jpg',
        'password' => bcrypt('password22'),
    ],
    [
        'restaurant_name' => 'Piadineria Emilia',
        'email' => 'info@piadineriaemilia.com',
        'address' => 'Via Rizzoli, 45',
        'vat_number' => 'IT22234567890',
        'phone_number' => '222-345-6789',
        'img' => 'uploads/piadineria_emilia.jpg',
        'password' => bcrypt('password23'),
    ],
    [
        'restaurant_name' => 'Steakhouse Milanese',
        'email' => 'info@steakhousemilanese.com',
        'address' => 'Via Dante, 16',
        'vat_number' => 'IT23234567890',
        'phone_number' => '232-345-6789',
        'img' => 'uploads/steakhouse_milanese.jpg',
        'password' => bcrypt('password24'),
    ],
    [
        'restaurant_name' => 'Pescheria Veneziana',
        'email' => 'info@pescheriaveneziana.com',
        'address' => 'Campo Santa Margherita',
        'vat_number' => 'IT24234567890',
        'phone_number' => '242-345-6789',
        'img' => 'uploads/pescheria_veneziana.jpg',
        'password' => bcrypt('password25'),
    ],
    [
        'restaurant_name' => 'Fiorentina Vegetariana',
        'email' => 'info@fiorentinavegetariana.com',
        'address' => "Via de' Tornabuoni, 5",
        'vat_number' => 'IT25234567890',
        'phone_number' => '252-345-6789',
        'img' => 'uploads/fiorentina_vegetariana.jpg',
        'password' => bcrypt('password26'),
    ],
    [
        'restaurant_name' => 'Vegano Palermitano',
        'email' => 'info@veganopalermitano.com',
        'address' => 'Via Vittorio Emanuele, 123',
        'vat_number' => 'IT26234567890',
        'phone_number' => '262-345-6789',
        'img' => 'uploads/vegano_palermitano.jpg',
        'password' => bcrypt('password27'),
    ],
    [
        'restaurant_name' => 'Pasta e Basta',
        'email' => 'info@pastaebasta.com',
        'address' => 'Via Appia, 14',
        'vat_number' => 'IT27234567890',
        'phone_number' => '272-345-6789',
        'img' => 'uploads/pasta_e_basta.jpg',
        'password' => bcrypt('password28'),
    ],
    [
        'restaurant_name' => 'Pizza & Amore',
        'email' => 'info@pizzaeamore.com',
        'address' => 'Via Cola di Rienzo, 77',
        'vat_number' => 'IT28234567890',
        'phone_number' => '282-345-6789',
        'img' => 'uploads/pizza_e_amore.jpg',
        'password' => bcrypt('password29'),
    ],
    [
        'restaurant_name' => 'Piadina Romagnola',
        'email' => 'info@piadinaromagnola.com',
        'address' => 'Via Mazzini, 33',
        'vat_number' => 'IT29234567890',
        'phone_number' => '292-345-6789',
        'img' => 'uploads/piadina_romagnola.jpg',
        'password' => bcrypt('password30'),
    ],
    [
        'restaurant_name' => 'Carne e Passione',
        'email' => 'info@carnepassione.com',
        'address' => 'Corso Sempione, 22',
        'vat_number' => 'IT30234567890',
        'phone_number' => '302-345-6789',
        'img' => 'uploads/carne_e_passione.jpg',
        'password' => bcrypt('password31'),
    ],
    [
        'restaurant_name' => 'Ristorante al Mare',
        'email' => 'info@ristorantealmare.com',
        'address' => 'Lungomare Dante, 5',
        'vat_number' => 'IT31234567890',
        'phone_number' => '312-345-6789',
        'img' => 'uploads/ristorante_al_mare.jpg',
        'password' => bcrypt('password32'),
    ],
    [
        'restaurant_name' => 'Veg & Joy',
        'email' => 'info@vegjoy.com',
        'address' => 'Via dei Fiori, 16',
        'vat_number' => 'IT32234567890',
        'phone_number' => '322-345-6789',
        'img' => 'uploads/veg_joy.jpg',
        'password' => bcrypt('password33'),
    ],
    [
        'restaurant_name' => 'Senza Glutine Bistro',
        'email' => 'info@senzaglutinebistro.com',
        'address' => 'Via Gluten Free, 9',
        'vat_number' => 'IT33234567890',
        'phone_number' => '332-345-6789',
        'img' => 'uploads/senza_glutine_bistro.jpg',
        'password' => bcrypt('password34'),
    ],
    [
        'restaurant_name' => 'Ristorante La Rosa',
        'email' => 'info@larosa.com',
        'address' => 'Via Rosetta, 8',
        'vat_number' => 'IT34234567890',
        'phone_number' => '342-345-6789',
        'img' => 'uploads/ristorante_la_rosa.jpg',
        'password' => bcrypt('password35'),
    ],
    [
        'restaurant_name' => 'Terra e Cielo',
        'email' => 'info@terraecielo.com',
        'address' => 'Via Paradiso, 12',
        'vat_number' => 'IT35234567890',
        'phone_number' => '352-345-6789',
        'img' => 'uploads/terra_e_cielo.jpg',
        'password' => bcrypt('password36'),
    ],
    [
        'restaurant_name' => 'Burger Italiano',
        'email' => 'info@burgeritaliano.com',
        'address' => 'Via del Burger, 44',
        'vat_number' => 'IT36234567890',
        'phone_number' => '362-345-6789',
        'img' => 'uploads/burger_italiano.jpg',
        'password' => bcrypt('password37'),
    ],
    [
        'restaurant_name' => 'Pasta Fresca e Vino',
        'email' => 'info@pastafrescavino.com',
        'address' => 'Via Vinicio, 67',
        'vat_number' => 'IT37234567890',
        'phone_number' => '372-345-6789',
        'img' => 'uploads/pasta_fresca_vino.jpg',
        'password' => bcrypt('password38'),
    ],
    [
        'restaurant_name' => 'Pesce Azzurro',
        'email' => 'info@pesceazzurro.com',
        'address' => 'Via Marina, 21',
        'vat_number' => 'IT38234567890',
        'phone_number' => '382-345-6789',
        'img' => 'uploads/pesce_azzurro.jpg',
        'password' => bcrypt('password39'),
    ],
    [
        'restaurant_name' => 'Ristorante Montagna',
        'email' => 'info@ristorantemontagna.com',
        'address' => 'Via Monte Bianco, 5',
        'vat_number' => 'IT39234567890',
        'phone_number' => '392-345-6789',
        'img' => 'uploads/ristorante_montagna.jpg',
        'password' => bcrypt('password40'),
    ],
    [
        'restaurant_name' => 'Verde Vegano',
        'email' => 'info@verdevegano.com',
        'address' => 'Via Verde, 17',
        'vat_number' => 'IT41234567890',
        'phone_number' => '412-345-6789',
        'img' => 'uploads/verde_vegano.jpg',
        'password' => bcrypt('password41'),
    ],
    [
        'restaurant_name' => 'Il Piattone',
        'email' => 'info@ilpiattone.com',
        'address' => 'Via delle Olive, 23',
        'vat_number' => 'IT42234567890',
        'phone_number' => '422-345-6789',
        'img' => 'uploads/il_piattone.jpg',
        'password' => bcrypt('password42'),
    ],
    [
        'restaurant_name' => 'Pasta al Dente',
        'email' => 'info@pastaldente.com',
        'address' => 'Corso Alberoni, 33',
        'vat_number' => 'IT43234567890',
        'phone_number' => '432-345-6789',
        'img' => 'uploads/pasta_al_dente.jpg',
        'password' => bcrypt('password43'),
    ],
    [
        'restaurant_name' => 'Pizza & Cuore',
        'email' => 'info@pizzaecuore.com',
        'address' => 'Via del Sole, 14',
        'vat_number' => 'IT44234567890',
        'phone_number' => '442-345-6789',
        'img' => 'uploads/pizza_e_cuore.jpg',
        'password' => bcrypt('password44'),
    ],
    [
        'restaurant_name' => 'Carnevale di Sapori',
        'email' => 'info@carnavaledisapori.com',
        'address' => 'Via Festiva, 9',
        'vat_number' => 'IT45234567890',
        'phone_number' => '452-345-6789',
        'img' => 'uploads/carnevale_di_sapori.jpg',
        'password' => bcrypt('password45'),
    ],
    [
        'restaurant_name' => 'Ristorante al Ponte',
        'email' => 'info@alponte.com',
        'address' => 'Via Ponte Vecchio, 6',
        'vat_number' => 'IT46234567890',
        'phone_number' => '462-345-6789',
        'img' => 'uploads/ristorante_al_ponte.jpg',
        'password' => bcrypt('password46'),
    ],
    [
        'restaurant_name' => 'Trattoria Il Fieno',
        'email' => 'info@ilfieno.com',
        'address' => 'Via Campagnola, 21',
        'vat_number' => 'IT47234567890',
        'phone_number' => '472-345-6789',
        'img' => 'uploads/trattoria_il_fieno.jpg',
        'password' => bcrypt('password47'),
    ],
    [
        'restaurant_name' => 'Pizzeria Luna Piena',
        'email' => 'info@lunapiena.com',
        'address' => 'Via della Luna, 8',
        'vat_number' => 'IT48234567890',
        'phone_number' => '482-345-6789',
        'img' => 'uploads/pizzeria_luna_piena.jpg',
        'password' => bcrypt('password48'),
    ],
    [
        'restaurant_name' => 'Pesce d\'Oro',
        'email' => 'info@pescedoro.com',
        'address' => 'Via Marinara, 17',
        'vat_number' => 'IT49234567890',
        'phone_number' => '492-345-6789',
        'img' => 'uploads/pesce_doro.jpg',
        'password' => bcrypt('password49'),
    ],
    [
        'restaurant_name' => 'Orto e Cucina',
        'email' => 'info@ortoecucina.com',
        'address' => 'Via del Giardino, 11',
        'vat_number' => 'IT50234567890',
        'phone_number' => '502-345-6789',
        'img' => 'uploads/orto_e_cucina.jpg',
        'password' => bcrypt('password50'),
    ],
    [
        'restaurant_name' => 'Ristorante Delizia',
        'email' => 'info@delizia.com',
        'address' => 'Via delle Delizie, 5',
        'vat_number' => 'IT51234567890',
        'phone_number' => '512-345-6789',
        'img' => 'uploads/ristorante_delizia.jpg',
        'password' => bcrypt('password51'),
    ],
    [
        'restaurant_name' => 'Vegano e Felice',
        'email' => 'info@veganofelice.com',
        'address' => 'Corso Felicita, 13',
        'vat_number' => 'IT52234567890',
        'phone_number' => '522-345-6789',
        'img' => 'uploads/vegano_e_felice.jpg',
        'password' => bcrypt('password52'),
    ],
    [
        'restaurant_name' => 'Panino e Fantasia',
        'email' => 'info@paninoefantasia.com',
        'address' => 'Via Panettiere, 3',
        'vat_number' => 'IT53234567890',
        'phone_number' => '532-345-6789',
        'img' => 'uploads/panino_e_fantasia.jpg',
        'password' => bcrypt('password53'),
    ],
    [
        'restaurant_name' => 'Dolce Vita Pizzeria',
        'email' => 'info@dolcevitapizza.com',
        'address' => 'Via Roma, 44',
        'vat_number' => 'IT54234567890',
        'phone_number' => '542-345-6789',
        'img' => 'uploads/dolce_vita_pizza.jpg',
        'password' => bcrypt('password54'),
    ],
    [
        'restaurant_name' => 'Il Gusto della Pasta',
        'email' => 'info@gustopasta.com',
        'address' => 'Via Garibaldi, 91',
        'vat_number' => 'IT55234567890',
        'phone_number' => '552-345-6789',
        'img' => 'uploads/gusto_pasta.jpg',
        'password' => bcrypt('password55'),
    ],
    [
        'restaurant_name' => 'La Piadina Felice',
        'email' => 'info@piadinafelice.com',
        'address' => 'Via Emilia, 27',
        'vat_number' => 'IT56234567890',
        'phone_number' => '562-345-6789',
        'img' => 'uploads/piadina_felice.jpg',
        'password' => bcrypt('password56'),
    ],
    [
        'restaurant_name' => 'Bistecca e Vino',
        'email' => 'info@bisteccavino.com',
        'address' => 'Via Firenze, 39',
        'vat_number' => 'IT57234567890',
        'phone_number' => '572-345-6789',
        'img' => 'uploads/bistecca_vino.jpg',
        'password' => bcrypt('password57'),
    ],
    [
        'restaurant_name' => 'Mare Blu',
        'email' => 'info@mareblu.com',
        'address' => 'Via Litoranea, 21',
        'vat_number' => 'IT58234567890',
        'phone_number' => '582-345-6789',
        'img' => 'uploads/mare_blu.jpg',
        'password' => bcrypt('password58'),
    ],
    [
        'restaurant_name' => 'Oasi Vegetariana',
        'email' => 'info@oasivegetariana.com',
        'address' => 'Via Verdi, 46',
        'vat_number' => 'IT59234567890',
        'phone_number' => '592-345-6789',
        'img' => 'uploads/oasi_vegetariana.jpg',
        'password' => bcrypt('password59'),
    ],
    [
        'restaurant_name' => 'Terra Vegana',
        'email' => 'info@terravegana.com',
        'address' => 'Corso Vegan, 12',
        'vat_number' => 'IT60234567890',
        'phone_number' => '602-345-6789',
        'img' => 'uploads/terra_vegana.jpg',
        'password' => bcrypt('password60'),
    ],
    [
        'restaurant_name' => 'Ristorante Senza Glutine',
        'email' => 'info@senzaglutine.com',
        'address' => 'Via Celiaci, 9',
        'vat_number' => 'IT61234567890',
        'phone_number' => '612-345-6789',
        'img' => 'uploads/senza_glutine.jpg',
        'password' => bcrypt('password61'),
    ],
    [
        'restaurant_name' => 'Pizza & Tradizione',
        'email' => 'info@pizzatradizione.com',
        'address' => 'Via Napoli, 66',
        'vat_number' => 'IT62234567890',
        'phone_number' => '622-345-6789',
        'img' => 'uploads/pizza_tradizione.jpg',
        'password' => bcrypt('password62'),
    ],
    [
        'restaurant_name' => 'Pasta e Brisa',
        'email' => 'info@pastaebrisa.com',
        'address' => 'Via Spaghetti, 32',
        'vat_number' => 'IT63234567890',
        'phone_number' => '632-345-6789',
        'img' => 'uploads/pasta_e_brisa.jpg',
        'password' => bcrypt('password63'),
    ],
    [
        'restaurant_name' => 'Piadina & Co',
        'email' => 'info@piadinaco.com',
        'address' => 'Corso Romagnolo, 45',
        'vat_number' => 'IT64234567890',
        'phone_number' => '642-345-6789',
        'img' => 'uploads/piadina_co.jpg',
        'password' => bcrypt('password64'),
    ],
    [
        'restaurant_name' => 'Grill Master',
        'email' => 'info@grillmaster.com',
        'address' => 'Via Carbonara, 29',
        'vat_number' => 'IT65234567890',
        'phone_number' => '652-345-6789',
        'img' => 'uploads/grill_master.jpg',
        'password' => bcrypt('password65'),
    ],
    [
        'restaurant_name' => 'Pesce e Basta',
        'email' => 'info@pesceebasta.com',
        'address' => 'Via Marina, 53',
        'vat_number' => 'IT66234567890',
        'phone_number' => '662-345-6789',
        'img' => 'uploads/pesce_fresco.jpg',
        'password' => bcrypt('password66'),
    ],
    [
        'restaurant_name' => 'Pizza al Tramonto',
        'email' => 'info@pizzatramonto.com',
        'address' => 'Via Sunset, 15',
        'vat_number' => 'IT67234567890',
        'phone_number' => '672-345-6789',
        'img' => 'uploads/pizza_tramonto.jpg',
        'password' => bcrypt('password67'),
    ],
    [
        'restaurant_name' => 'Primavera Primi Piatti',
        'email' => 'info@primaveraprimi.com',
        'address' => 'Via Primavera, 22',
        'vat_number' => 'IT68234567890',
        'phone_number' => '682-345-6789',
        'img' => 'uploads/primavera_primi.jpg',
        'password' => bcrypt('password68'),
    ],
    [
        'restaurant_name' => 'Pastificio Centrale',
        'email' => 'info@pastificiocentrale.com',
        'address' => 'Via Del Centro, 33',
        'vat_number' => 'IT69234567890',
        'phone_number' => '692-345-6789',
        'img' => 'uploads/pastificio_centrale.jpg',
        'password' => bcrypt('password69'),
    ],
    [
        'restaurant_name' => 'La Piadina Romagnola',
        'email' => 'info@piadinromagnola.com',
        'address' => 'Via Emilia, 44',
        'vat_number' => 'IT70234567890',
        'phone_number' => '702-345-6789',
        'img' => 'uploads/piadina_romagnola.jpg',
        'password' => bcrypt('password70'),
    ],
    [
        'restaurant_name' => 'Carne e Vino',
        'email' => 'info@carnevino.com',
        'address' => 'Via Del Vino, 51',
        'vat_number' => 'IT71234567890',
        'phone_number' => '712-345-6789',
        'img' => 'uploads/carne_vino.jpg',
        'password' => bcrypt('password71'),
    ],
    [
        'restaurant_name' => "L'Oceano Fresco",
        'email' => 'info@oceanofresco.com',
        'address' => 'Via Oceano, 66',
        'vat_number' => 'IT72234567890',
        'phone_number' => '722-345-6789',
        'img' => 'uploads/oceano_fresco.jpg',
        'password' => bcrypt('password72'),
    ],
    [
        'restaurant_name' => 'Erba Vegana',
        'email' => 'info@erbavegana.com',
        'address' => 'Via Green, 77',
        'vat_number' => 'IT73234567890',
        'phone_number' => '732-345-6789',
        'img' => 'uploads/verde_vegano.jpg',
        'password' => bcrypt('password73'),
    ],
    [
        'restaurant_name' => 'Senza Glutine Restaurant',
        'email' => 'info@senzaglutinerestaurant.com',
        'address' => 'Via Celiaci, 88',
        'vat_number' => 'IT74234567890',
        'phone_number' => '742-345-6789',
        'img' => 'uploads/senzaglutine_bistro.jpg',
        'password' => bcrypt('password74'),
    ],
    [
        'restaurant_name' => 'Pizza Paradiso',
        'email' => 'info@pizzaparadiso.com',
        'address' => 'Via Paradiso, 99',
        'vat_number' => 'IT75234567890',
        'phone_number' => '752-345-6789',
        'img' => 'uploads/pizza_paradiso.jpg',
        'password' => bcrypt('password75'),
    ],
    [
        'restaurant_name' => 'Pasta Perfetta',
        'email' => 'info@pastaperfetta.com',
        'address' => 'Via Della Perfezione, 104',
        'vat_number' => 'IT76234567890',
        'phone_number' => '762-345-6789',
        'img' => 'uploads/pasta_perfetta.jpg',
        'password' => bcrypt('password76'),
    ],
    [
        'restaurant_name' => 'Piadina & Friends',
        'email' => 'info@piadinafriends.com',
        'address' => 'Corso Amici, 117',
        'vat_number' => 'IT77234567890',
        'phone_number' => '772-345-6789',
        'img' => 'uploads/piadina_friends.jpg',
        'password' => bcrypt('password77'),
    ],
    [
        'restaurant_name' => 'Carne Cortile',
        'email' => 'info@carnecortile.com',
        'address' => 'Via Del Cortile, 130',
        'vat_number' => 'IT78234567890',
        'phone_number' => '782-345-6789',
        'img' => 'uploads/carne_cortile.jpg',
        'password' => bcrypt('password78'),
    ],
    [
        'restaurant_name' => 'Pesce Porta',
        'email' => 'info@pesceporta.com',
        'address' => 'Via Della Porta, 143',
        'vat_number' => 'IT79234567890',
        'phone_number' => '792-345-6789',
        'img' => 'uploads/pesce_porta.jpg',
        'password' => bcrypt('password79'),
    ],
    [
        'restaurant_name' => 'Ristorante Arcobaleno Vegetariano',
        'email' => 'info@arcobalenoveg.com',
        'address' => 'Via Arcobaleno, 156',
        'vat_number' => 'IT80234567890',
        'phone_number' => '802-345-6789',
        'img' => 'uploads/arcobaleno_vegetariano.jpg',
        'password' => bcrypt('password80'),
    ],
];


return $usersData;
